### ISSUE TITLE
7.0.0 types file is incorrectly referenced

### ISSUE THREAD

**Issue by mtraynham** [beaugunderson/ip-address#114]
The `package.json` file has `"types": "dist/index.d.ts"`, but that file doesn't exist and it's likely meant to be `"types": "dist/ip-address.d.ts"`

<img width="415" alt="Screen Shot 2020-10-03 at 8 47 29 AM" src="https://user-images.githubusercontent.com/5741321/94992052-47ce6600-0555-11eb-8245-dd6596be51c1.png">
<img width="321" alt="Screen Shot 2020-10-03 at 8 47 21 AM" src="https://user-images.githubusercontent.com/5741321/94992057-4ac95680-0555-11eb-988e-94c1924cce88.png">

**Comment by beaugunderson** [comment]
you’re right, this changed during development; need to add a linter to
catch that! 7.0.1 coming momentarily
