### ISSUE TITLE
Is isCorrect a replacement for isValid?

### ISSUE THREAD

**Issue by lekoaf** [beaugunderson/ip-address#115]
While updating to `ip-address` v7 I noticed that `isValid` is gone.

Is `isCorrect` a replacement for that?

```javascript
const address = new Address4(unknownAddress)
address.isCorrect()
```
You suggest using a `try / catch` but my problem is that my linter complains both when I do this:

```javascript
try {
      new Address4(address)
} catch {
      return 'Invalid address'
}
```

`Do not use 'new' for side effects.`

and this:

```javascript
try {
      const ipv4Address = new Address4(address)
} catch {
      return 'Invalid address'
}
```
```
'ipv4Address' is declared but its value is never read. ts(6133)
'ipv4Address' is assigned a value but never used. eslint@typescript-eslint/no-unused-vars
```

**Comment by lekoaf** [comment]
After digging through the code a bit, it seems that you will throw and error if the address is not vaild as soon as you instantiate the `Address4` class. So I guess `isCorrect` is not the correct way to go.

**Comment by lekoaf** [comment]
Solved it for now by using the first `try / catch` with an `eslint-disable-next-line` comment. But that doesn't seem like the correct way  to do it.

**Comment by beaugunderson** [comment]
ah, for this case (when you only want to know if an address is valid but
don’t want to do anything else with it) I can add a static method

**Comment by lekoaf** [comment]
That would be sweet. In this case I just use it as a "return early" check before doing other stuff. But I use other parts of this library in other functions.

**Comment by nrone** [comment]
I'm in the same boat. Useing the .isValid() to validate if the input is correct in a custom Angular validator.
`      if (version === 4) {
        valid = new Address4(control.value).isValid();
      } else if (version === 6) {
        valid = new Address6(control.value).isValid();
      }
      if (!valid) {
        return { 'invalidIp': true };
      }`

**Comment by jcheng5** [comment]
Same here, `isValid` is mostly what I was using this library for.

**Comment by beaugunderson** [comment]
@lekoaf @nrone @jcheng5 I added a static `isValid` method in the just-released 7.1.0; you can use it like this:

```js
if (Address6.isValid('::')) {
  console.log('valid!');
} else {
  console.log('invalid!');
}
```

**Comment by gramakri** [comment]
It seems this static method is missing in the docs - https://ip-address.js.org/#address4

**Comment by beaugunderson** [comment]
The docs have atrophied quite a bit unfortunately--will see if I can update soon.

**Comment by gramakri** [comment]
@beaugunderson no worries. Also the source code links go nowhere.

![Image](https://github.com/user-attachments/assets/7c43334b-e34e-4c63-8c3a-84edfbee9c99)
