### ISSUE TITLE
0:0:0:0:0:0:0:1  and  0:0:0:0:0:0:0:0  invalid 

### ISSUE THREAD

**Issue by zctya** [beaugunderson/ip-address#121]
![WX20201027-103509](https://user-images.githubusercontent.com/10741844/97250082-22750500-1840-11eb-9f01-efefbee3484f.png)

**Comment by beaugunderson** [comment]
the fact that you got an Address6 and not an exception means it’s valid—can
you help me understand what’s different than what you expect to happen? :)

**Comment by zctya** [comment]
var Address6 = require('ip-address').Address6;
var address6 = new Address6('0:0:0:0:0:0:0:0')
address6.isCorrect()  //  return false except true

**Comment by beaugunderson** [comment]
that’s not what isCorrect is for—“::” is the “correct” representation of
that address; I think that function should be renamed to make it more
obvious what it does :)

you can use the static Address6.isValid (added in 7.1.0) for checking
validity

**Comment by beaugunderson** [comment]
to further explain; if you visit v6decode.com (which uses this library) and enter an address you can see how the various flags work out, e.g. for 0:0:0:0:0:0:0:0:

![image](https://user-images.githubusercontent.com/61791/97323575-2e57cb80-182e-11eb-9750-6f9c776f4c18.png)

the definition of "correct" is the one detailed here: https://tools.ietf.org/html/rfc5952#page-10

**Comment by beaugunderson** [comment]
### pre-7.0.0

```js
const a = new Address6('0:0:0:0:0:0:0:0');
a.isValid(); // true

const b = new Address6('invalid address');
a.isValid(); // false
```

### in 7.0.0 and above

```js
const a = new Address6('0:0:0:0:0:0:0:0'); // doesn't throw an exception, so you know the address is valid

const b = new Address6('invalid address'); // throws an exception

// or you can use the new static method
Address6.isValid('0:0:0:0:0:0:0:0'); // true

Address6.isValid('invalid address'); // false
```

**Comment by zctya** [comment]
Thanks

**Comment by zctya** [comment]
**in 7.1.0 passed**
Address6.isValid('0:0:0:0:0:0:0:0'); // true

Address6.isValid('invalid address'); // false
