### ISSUE TITLE
Leading zeroes should not make address incorrect

### ISSUE THREAD

**Issue by asergeyev** [beaugunderson/ip-address#130]
the isCorrect() on Address6 currently will return false if the address includes leading 0 in segment of the IP. I did not check v4 as it's not popular to keep zeroes around in it.

Quick test:
![image](https://user-images.githubusercontent.com/715656/113754762-8ea44080-96dd-11eb-9a17-1b6680906077.png)

P.s.
Also this prevents positive isCorrect on canonicalForm returned IP address; seems silly

**Comment by beaugunderson** [comment]
yes, isCorrect does not mean “is it valid”, it should probably be renamed
to reflect what it actually means which is something closer to “is it the
most compact representation it can be” :)

so in this case the behavior is correct, the leading zero can be omitted
for a more compact address

**Comment by asergeyev** [comment]
Gotcha, so in case of invalid address it's guaranteed to throw an exception?

**Comment by asergeyev** [comment]
Ah, silly me it's already isCorrect/correctForm pair. Thanks for everything!
