### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by bodinsamuel** [beaugunderson/ip-address#139]
Hello,

Thanks for this project, it would be awesome to provide a changelog, even a small one. 
It helps when there is a major like this v8 but we don't know what really changed, if there is breaking changes or not, etc...

Thanks

**Comment by beaugunderson** [comment]
I rely on CHANGELOGs in other projects and not having one here is a massive oversight! Will add going forward.

**Comment by floriannari** [comment]
Hello,

Has a changelog finally been provided?
(I couldn't find it)

Thanks 🙏
