### ISSUE TITLE
Package subpath './dist/cjs/lib/ipv4' is not defined by "exports"

### ISSUE THREAD

**Issue by zotakk4o** [beaugunderson/ip-address#146]
Can someone please explain why the following error occurs in 8.1.0 with Node v12.22.5? With version 12.9.0 it does not appear.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/cjs/lib/ipv4' is not defined by "exports" in path-to-my-ip-address-location\ip-address\v8\node_modules\ip-address\package.json imported from path-to-my-ip-address-location\ip-address\dist\cjs\ip-address.js

**Comment by zotakk4o** [comment]
If "exports" section from package.json is removed, the problem is gone.

**Comment by beaugunderson** [comment]
should be solved now with the simplification in 9.0.5
