### ISSUE TITLE
Converting IP Addresses for storage in mongodb

### ISSUE THREAD

**Issue by ddiguru** [beaugunderson/ip-address#23]
I’m looking to leverage your javascript-ipv6 IP Address parsing library to do the following:
* validate v4 or v6 addresses
* calculate network address from address/prefix provided
* calculate start & end IP addresses for network
* perform necessary conversion to store either v4 or v6 start and end addresses in mongodb

I have sort of hit a wall on the last bullet point. 

I had to write a function to parse the parsedAddress into an array of decimal parts. Then, I pass this array of decimals into a function to return them as an Array of Bytes. This allows me to create a new Buffer(ByteArray) for passing into mongodb via mongoose. 

Does that sound right to you? Can you think of a better or easier way to satisfy that last bullet? BSON doesn’t support BigInteger, so i have to store in BinData type. 

Here’s the gist of the code… I got my inspiration from ipaddr.js, another parsing library on github. If you think this is right and the way to go, any chance you could incorporate it to your library? 

```javascript
var v6 = require(‘ipv6’).v6;

var v6addr = new v6.Address('2001:470:8759::/64');
var parts = toDecimalParts(v6addr.parsedAddress);
var byteArray = toByteArray(parts);
var buf = new Buffer(byteArray);

/* convert parsedAddr to array of decimals */
function toDecimalParts(parsedAddr) {
    var arr = [];
    parsedAddr.forEach(function(n) {
        arr.push(parseInt(n, 16));
    });
    return arr;
}

/* convert parts to array of bytes */
function toByteArray(parts) {
    var bytes, part, _i, _len, _ref;
    bytes = [];
    _ref = parts;
    _len = _ref.length;
    for(_i=0; _i < _len; _i++) {
        part = _ref[_i];
        bytes.push(part >> 8);
        bytes.push(part & 0xff);
    }
    return bytes;
}
```

**Comment by beaugunderson** [comment]
I think BigInteger has most of what you need, though I do notice it varies slightly from your output:

```node
> a = new v6.Address('2001:470:8759::/64')

> toByteArray(toDecimalParts(a.parsedAddress))
[ 32,
  1,
  4,
  112,
  135,
  89,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0 ]

> a.bigInteger().toByteArray()
[ 32,
  1,
  4,
  112,
  -121,
  89,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0 ]
```

I think all you'd need to do is write a function to get the array of bytes back into a BigInteger (which is something I'd welcome for this library since the `BigInteger` library I'm using doesn't have that function). :)

I'd probably call it `fromByteArray`.

**Comment by ddiguru** [comment]
Very odd that comes out with a negative number for the 5th byte or 87. It should be 135. It looks like what i'm doing is just fine. I can't think of an easier way to get binary(ipv6) address. Can you?

**Comment by beaugunderson** [comment]
Oh, the difference is that jsbn uses signed 8 bit integers (so it can't represent 135 as 135).

**Comment by ddiguru** [comment]
I'd love it if you'd include the code i supplied. works great.

**Comment by beaugunderson** [comment]
I will add support for toByteArray and fromByteArray but I'm not going to duplicate code already in jsbn. :)

**Comment by ddiguru** [comment]
You've already got the equivalent of toDecimalParts() with your v6.Address.prototype.decimal, it's just that it doesn't create an array, it formats the data and joins w/ ':'. Oh no, yeah i wouldn't. These are convenient methods for preparing ipv4 and/or ipv6 IPs for storing in binary form. Thanks!

**Comment by beaugunderson** [comment]
OK, I've added `toByteArray`, `fromByteArray`, `toUnsignedByteArray`, and `fromUnsignedByteArray` in 4.2.0. :)
