### ISSUE TITLE
Converting an `IPv4 mapped` to IPv4 format

### ISSUE THREAD

**Issue by diasdavid** [beaugunderson/ip-address#24]
I've been spelunking the unit tests to understand what would be the most elegant way to convert and addr `::ffff:127.0.0.1` to its IPv4 counter part. Thoughts?

Thank you :)

**Comment by beaugunderson** [comment]
Try the new `tov4` function in the just-released 4.1.0. :)

You can use `new v6.Address('::ffff:127.0.0.1').tov4().correctForm()` to get `127.0.0.1`.
