### ISSUE TITLE
Dependency sprintf is not maintained anymore

### ISSUE THREAD

**Issue by michel-zimmer** [beaugunderson/ip-address#28]
[sprintf](https://www.npmjs.com/package/sprintf) is not maintained anymore.
[sprintf-js](https://www.npmjs.com/package/sprintf-js) seems to be the way to go.

Is it necessary to adopt?

# From the README.md from sprintf

## Disclaimer

This was originally just an adoption of a browser library to node.js.  
Since that library is now itself a node.js module, you should use that one: [alexei/sprintf.js](https://github.com/alexei/sprintf.js)

Or just install it via npm:

    npm install sprintf-js

There is also a [built-in util.format](http://nodejs.org/api/util.html#util_util_format_format).

## Install

**This package is not maintained anymore. See Disclaimer above.**
[...]

**Comment by beaugunderson** [comment]
good catch, thanks!
