### ISSUE TITLE
BigInteger (jsbn) dependency not declared

### ISSUE THREAD

**Issue by stimg** [beaugunderson/ip-address#29]
After installing if I try ip.bigInteger() I get an error: "BigInteger is not a function". 
`bower install jsbn --save` helps.

If after that I try 
`ip.endAddress().bigInteger() < ip.startAddress().bigInteger()`
I get an error: `jsbn.js:182 Uncaught TypeError: this.toRadix is not a function(…)`

**Comment by beaugunderson** [comment]
hey @stimg; thanks for reporting this--`jsbn` is defined as a dependency in `package.json` at 0.0.0; how are you installing `ip-address`? (if you're using bower I don't have much experience with it but if you let me know your environment I'm happy to help debug)

the issue you're seeing now is that you've installed 0.1.0 of jsbn (which breaks things in a non-semver way); please try installing ip-address 5.2.0; I've upgraded to use jsbn 0.1.0 and fixed the issues it caused now. :sparkles:

**Comment by stimg** [comment]
hi @beaugunderson, :) I've installed it like
`bower install javascript-ipv6 --save`
javascript-ipv6 points to `git://github.com/gateprotect/javascript-ipv6.git` which is forked from your beaugunderson/ip-address, what I've found first. :) I can see here bower.json and package.json, but none of them has jsbn.js dependency, f.e. bower.js:
```
{
  "name": "javascript-ipv6",
  "main": "ipv6.js",
  "version": "3.0.0",
  "homepage": "https://github.com/beaugunderson/javascript-ipv6",
  "authors": [
    "Beau Gunderson <beau@beaugunderson.com>"
  ],
  "description": "A browser- and node-compatible library for parsing IPv6 addresses",
  "keywords": [
    "ipv6",
    "browser",
    "validation"
  ],
  "license": "MIT",
  "dependencies": {
    "sprintf": "*"
  },
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```

**Comment by beaugunderson** [comment]
ah, well, that fork is very old indeed :)

I haven't done anything specific to support bower in ip-address, my thinking was that to include it in the browser people would use something like `browserify` (since ip-address and all of its dependences lives on npm).

jsbn 0.0.0 and 0.1.0 are npm versions, not bower versions, hence the confusion there. :)

**Comment by stimg** [comment]
I'm using `GruntJS` for app building, so `Browserify` is not really suitable for me in the case. I'd like to use your lib. The only thing I need now is to define if the given IPv6 is in the subnet. As far as I understand, I need to compare start and end addresses of the subnet with given IP. These are BigIntegers. Are we going to solve the issue? I could fork your branch, move to `bigintegers.js` and try to incorporate it into bower components. What do you think?

**Comment by beaugunderson** [comment]
i don't think grunt precludes you from using browserify (see [grunt-browserify](https://github.com/jmreidy/grunt-browserify)) but i do understand not wanting to change your whole toolchain just to use a module! :)

i think what needs to happen is for me to add a bower.json to ip-address and specify dependencies--the only issue i foresee is that some dependencies may not exist in both npm and bower.

relatedly, another issue i created was #30, to switch from jsbn (not very widely-used anymore) to bignumber.js (maybe that's what you meant by bigintegers.js?)

that said, i am interested in making these changes (or you can, if you have the time and want to)!

**Comment by beaugunderson** [comment]
sorry, changed my mind again, i think big-integer is probably the best bet (the same on npm and bower); i'm looking at implementing that today

**Comment by stimg** [comment]
he-he, as it is always happens, I'm under time pressure. The app is ready, there was no request to check IPs, but I suppose it will come. So I think I have a bit time to play around. Will check if I can use `grunt-browserify` here.

Yes, very good idea to put deps into `bower.json`and yes, not all node mods are available for `bower`.

Yes, I saw your #30 and I've meant `bignumbers.js`, sorry. :)

I'd say you can just make changes in the `bower.js` since I don't know for sure which ones needed. Than I could test it and extend / correct / fix.. So may be step by step moving when we have time. :)

**Comment by stimg** [comment]
hey, you're so fast! super. thank you!

**Comment by beaugunderson** [comment]
@stimg no problem :) i've added a bower.json now, sprintf is identical within node/bower but jsbn is not; i found a `jsbn-amd` library that i believe works, and the `main` is set to `dist/jsbn.amd.js`, which includes all of the jsbn functionality i use... let me know if it works or if you need anything else changed on the bower side :)

**Comment by beaugunderson** [comment]
i also just published 5.3.0 which includes the bower.json

**Comment by stimg** [comment]
OK, will check it tomorrow. We have 22:30 now ;) Thank you again!

**Comment by beaugunderson** [comment]
no problem, let me know how it works :)

**Comment by stimg** [comment]
It looks like there is still some incompatibility with npm / amd syntax:
```
jsbn.amd.js:3 Uncaught ReferenceError: define is not defined(anonymous function) @ jsbn.amd.js:3(anonymous function) @ jsbn.amd.js:4
index.js:1 Uncaught ReferenceError: exports is not defined(anonymous function) @ index.js:1
ipv6.js:1 Uncaught SyntaxError: Unexpected token ILLEGAL
```

**Comment by stimg** [comment]
BTW, I've checked `grunt-browserify` and it really not suitable for me, because all `Angular`modules use ECMA6 syntax, and only one will use CJS. So for this one module I must install `grunt-browserify`, create grunt task to build this module and register it in the grunt build task. I bit complicated. 

I think this is pretty cool to write apps with `grunt-browserify` from the scratch using CJS syntax, but to have fifty-fifty ECMA / CJS is not a good idea IMHO. :) But anyway, thanks for the hint! ;)

**Comment by beaugunderson** [comment]
@stimg ah, sorry!

i've just released 5.6.0 which uses a new jsbn-npm-equivalent module that I've created that should include all of the required jsbn functionality. give it a try?

**Comment by stimg** [comment]
yes, I see 5.6.0. Again:
`index.js:1 Uncaught ReferenceError: exports is not defined`:)

**Comment by beaugunderson** [comment]
ah, OK, so now the dependencies work but we're up against the fact that wiredep does not do any translation of node-style modules.

how do you feel about something like this:

http://www.mattburkedev.com/export-a-global-to-the-window-object-with-browserify/

this way you could do a one-off run of browserify from the CLI to create a JS file you can include in your page that exports Address4 and Address6 to the window namespace. the dependencies will come from npm, which solves the issue of having different dependencies.

in thinking about it maybe i can create this file in a dist/ directory and list it as the `main` of the bower.json... i will investigate this now. :)

**Comment by beaugunderson** [comment]
@stimg ok, please try 5.7.0, if it works i'm very happy with this approach :)

**Comment by stimg** [comment]
he-he this is the stuff I wrote about above. I don't want `browserify`in the project now, since they want I deliver prod version on Monday. I could make a fork and translate it CJS --> ECMA6. :-/

The idea to make different folders for npm and browser could also work. You can just define in the bower.json another files to include.

**Comment by stimg** [comment]
Last version works! :-D

**Comment by beaugunderson** [comment]
excellent! sorry it took so long :)

---

**Comment by stimg** [comment]
what?! too long! That was very fast! Great job Beau! Thanks a lot. Comparison of the BigIntegers works as well. Super! I'm happy. You get a star from me. ;)

**Comment by beaugunderson** [comment]
thanks, glad to help :)
