### ISSUE TITLE
Move from jsbn to another library

### ISSUE THREAD

**Issue by beaugunderson** [beaugunderson/ip-address#30]
jsbn recently made a backwards-incompatible breaking change in a minor version

[bignumber.js](https://github.com/MikeMcl/bignumber.js) seems like it's used by many more people

**Comment by beaugunderson** [comment]
so bignumber.js lacks any integer-only methods like .xor, .and, etc. and therefor isn't a good fit; all the other biginteger libraries i've found are lacking something (toByteArray, testBit)

**Comment by beaugunderson** [comment]
I think we're stuck with jsbn for the foreseeable future!

**Comment by Glandos** [comment]
Now that BigInt landed in browsers more than 3 years ago, there is also https://github.com/GoogleChromeLabs/jsbi that uses them if available. Will it fit your needs?

**Comment by beaugunderson** [comment]
it has `xor` and `and` but I don't see a method for testing a given bit or converting to a byte array (which we could write ourselves, but a bit more involved than just switching libraries and moving the calls to new names)

thanks for pointing out the library though!
