### ISSUE TITLE
Range overlapping

### ISSUE THREAD

**Issue by klimashkin** [beaugunderson/ip-address#32]
Hi!
Is it possible with library to check overlapping of two ips with CIDR?
Something like `new Address4('172.17.21.144/10').overlap('172.17.21.144/12')`

**Comment by beaugunderson** [comment]
not in one line like that but I'll add something simpler than the way you'd have to do it now :)

---

**Comment by beaugunderson** [comment]
@klimashkin sorry, I misunderstood your question--you want the [`isInSubnet` command](http://ip-address.js.org/#address4/isinsubnet)--though note that `isInSubnet` must be called with the smaller subnet as the argument :)

**Comment by klimashkin** [comment]
Yea, but `isOverlap` would be more convenient, don't need to think about smaller subnet position :)

**Comment by beaugunderson** [comment]
that's easy enough to implement, I'll add it :)

---
