### ISSUE TITLE
Address.isValid() fails on valid IPv6 address

### ISSUE THREAD

**Issue by RangerRick** [beaugunderson/ip-address#33]
I am attempting to parse the IPv6 address `2600:5800:f2a2:0000:0000:0000:0000:002c` and it fails with this error when I call `.isValid()` on the `Address6` object:

TypeError: undefined is not an object (near '...for (i = 0; i < address.length;...')

If I add it to your unit test data, I get:

```
  1) Valid IPv6 addresses 2600:5800:f2a2:0000:0000:0000:0000:002c is correct:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/address-test.js:111:39)
```

My production code that's failing is passed through webpack so it's hard to tell exactly where it's bailing, but I get this error in the browser backtrace:

```
Error: undefined is not an object (evaluating 'slice')
compact
correctForm

fn
regularInterceptedExpression
```

As far as I can tell, this is actually a valid IPv6 address (it certainly has been handed out by my router at work &lt;g&gt;).  Any ideas what's going wrong?  It seems to be bombing out in the `compact()` method.

**Comment by beaugunderson** [comment]
hm, what runtime are you using? (node, browser, other?)

I ask because I can't replicate this locally:

```
> a.canonicalForm()
'2600:5800:f2a2:0000:0000:0000:0000:002c'
> a.correctForm()
'2600:5800:f2a2::2c'
> a.isValid()
true
```

the unit test is a red herring; that failure is because `2600:5800:f2a2:0000:0000:0000:0000:002c` is not the "correct" form of the address, `2600:5800:f2a2::2c` is. "correct" here just means "the most compact representation, without leading zeroes, with only lower-case letters".

the runtime you're using & the smallest snippet that causes the error would be helpful in debugging this :)

**Comment by RangerRick** [comment]
This is inside a Cordova (WkWebView) browser on iOS that I'm seeing it.  So far I'm not able to replicate it in a simpler script so my first thought is webpack is doing something funky, but I'm seeing it even when I'm not doing any minification.  I've tried to replicate it with a simple one-liner that I hit with mobile safari and it doesn't happen.  My next step is to make a simple cordova project that just calls it immediately in index.html without any other junk to see if I can reproduce it there.

**Comment by beaugunderson** [comment]
@RangerRick is this still an issue for you?

**Comment by beaugunderson** [comment]
please reopen if you can replicate this again :)
