### ISSUE TITLE
Address6#toByteArray can return an array of length 17

### ISSUE THREAD

**Issue by Aaron1011** [beaugunderson/ip-address#40]
For example, the line `new Address6("ddef:6d91:558c:5a9b:41ff:8ea7:5a15:fa06").toByteArray().length` produces an array of length 17 (though the first element is set to 0).

I haven't looked into this issue much yet, but it appears to be caused by how [jsbn's](https://github.com/andyperlitch/jsbn) `toByteArray` function works.

**Comment by beaugunderson** [comment]
fixed in 5.8.7; thanks for reporting!
