### ISSUE TITLE
No dist folder in "5.8.4"

### ISSUE THREAD

**Issue by GuyShaanan** [beaugunderson/ip-address#46]
When installing version 5.8.4 via `npm install ip-address` there is no "dist" folder anymore.

Going back to 5.8.2 works.

**Comment by beaugunderson** [comment]
hey @GuyShaanan, I can add the `dist/` folder back to npm, what's your use case for using it that way though?

**Comment by GuyShaanan** [comment]
Hmm... seems like I've been using this in the wrong way.

I used to simply include the ip-addresses-globals.js in my Angular2 project, and not require individual modules.

Though many libraries do use a `dist/` folder for their "compiled" files, and offer a `.min.js` versions for production.

**Comment by GuyShaanan** [comment]
Hmm... seems like I've been using this in the wrong way.

I used to simply include the ip-addresses-globals.js in my Angular2 project, and not require individual modules.

Though many libraries do use a `dist/` folder for their "compiled" files, and offer a `.min.js` versions for production.

**Comment by beaugunderson** [comment]
@GuyShaanan not passing judgment on whether it's right or wrong, just wanted to understand how you were using it :)

added back in 5.8.6!
