### ISSUE TITLE
Address6.fromAddress4() can't parse IPv4 subnet.

### ISSUE THREAD

**Issue by ktanakaj** [beaugunderson/ip-address#48]
Hi, I found a problem about Address6.fromAddress4().

`var v6 = Address6.fromAddress4('192.168.1.0');
console.log(v6);`

> `Address6  {
  groups: 8,
  v4: true,
  subnet: '/128',
  subnetMask: 128,
  zone: '',
  address: '::ffff:192.168.1.0',
  addressMinusSuffix: '::ffff:192.168.1.0',
  elidedGroups: 5,
  elisionBegin: 0,
  elisionEnd: 5,
  valid: true,
  parsedAddress: [ '0', '0', '0', '0', '0', 'ffff', 'c0a8', '100' ] }`

It is good. There are no problem. But...

`var v6 = Address6.fromAddress4('192.168.1.0/31');
console.log(v6);`

> `Address6 {
  groups: 8,
  v4: true,
  subnet: '/31',
  subnetMask: 31,
  zone: '',
  address: '::ffff:192.168.1.0/31',
  parsedSubnet: '31',
  addressMinusSuffix: '::ffff:192.168.1.0',
  elidedGroups: 5,
  elisionBegin: 0,
  elisionEnd: 5,
  valid: true,
  parsedAddress: [ '0', '0', '0', '0', '0', 'ffff', 'c0a8', '100' ] }`

It is not good because this subnet for IPv4. I think the v6 should be `subnet; '/127'` and `subnetMask: 127`.

I solved by a following code. But I think this is problem need fix to the lib.
`var v6 = Address6.fromAddress4(ip);
if (v6.subnetMask <= 32) {
	v6.subnetMask += 96;
	v6.subnet = '/' + v6.subnetMask;
}`

Regards,
Koichi Tanaka

**Comment by beaugunderson** [comment]
fixed in 5.8.8; thanks for reporting!
