### ISSUE TITLE
sprintf is not defined when parsing ipv6 address

### ISSUE THREAD

**Issue by DariuszOstolski** [beaugunderson/ip-address#56]
This is on latest node package: ip-address@5.8.8

HTR:
let addr = IpAddress.Address6(someIpv6Address);

Result:
TypeError: sprintf is not a function
    at eval (https://xxx.xx.x.xxx:8002/node_modules/ip-address/lib/ipv6.js:659:12)
    at Array.map (native)
    at Address6.parse (https://xxx.xx.x.xxx:8002/node_modules/ip-address/lib/ipv6.js:658:19)
    at new Address6 (https://xxx.xx.x.xxx:8002/node_modules/ip-address/lib/ipv6.js:92:29)

Expected result: ipv6 address parsing does not cause a TypeError

**Comment by beaugunderson** [comment]
what build pipeline are you using?

**Comment by DariuszOstolski** [comment]
Its typescript in jit + systemjs loader, the problem does not occurs for ipv4 since its properly defined

**Comment by beaugunderson** [comment]
@DariuszOstolski not sure what to tell you, this seems like an issue in your build system since `sprintf` is defined the same way in every file:

```sh
$ ag sprintf | ag require
v6/helpers.js:3:var sprintf = require('sprintf-js').sprintf;
v6/regular-expressions.js:3:var sprintf = require('sprintf-js').sprintf;
ipv4.js:7:var sprintf = require('sprintf-js').sprintf;
ipv6.js:9:var sprintf = require('sprintf-js').sprintf;
v6/html.js:5:var sprintf = require('sprintf-js').sprintf;
```

**Comment by DariuszOstolski** [comment]
Indeed, I've just reinstalled it and it seems that is present, although I'm pretty sure that it wasn't. This is something I don't understand. Maybe it was deleted accidentally or something. Nevertheless thanks for your help.
