### ISSUE TITLE
IPv6 Scope enum is incorrect

### ISSUE THREAD

**Issue by charliematters** [beaugunderson/ip-address#61]
Hi,

In this file: https://github.com/beaugunderson/ip-address/blob/master/lib/v6/constants.js

You have entries for 15 (Global) and 16 (Reserved). This should instead be 14 and 15 (0xE and 0xF)

**Comment by beaugunderson** [comment]
@charliematters good catch, fixed in 5.8.9; thank you!

**Comment by charliematters** [comment]
Nice. Thanks!

**Comment by charliematters** [comment]
Hi again,

Thought it probably wasn't raising another issue, but it looks like "Realm Local" is missing as well on line 13?

I'm basing that on [this document](https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml)
