### ISSUE TITLE
Is it possible to use something more up-to-date than `cli` ?

### ISSUE THREAD

**Issue by lorem--ipsum** [beaugunderson/ip-address#65]
The package `cli` hasn't been updated in a year and it's used some very old dependencies (that yell at me each time I install npm modules). I'd be happy to help by submitting a PR if this is something @beaugunderson would think is worth it !

Thanks for the project :)

**Comment by beaugunderson** [comment]
@lorem--ipsum i can't actually find where `cli` is used now--where do you see it?

**Comment by lorem--ipsum** [comment]
My bad, I misread the output of `npm list` on my computer. Closing this. Thanks !
