### ISSUE TITLE
Does this work with Windows UNC?

### ISSUE THREAD

**Issue by pizzae** [beaugunderson/ip-address#66]
https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_UNC_path_names

E.g: can we get an ipv6 address without colons, for use in internet explorer?

**Comment by beaugunderson** [comment]
@pizzae yes, `microsoftTranscription()` is the function you want :)

you can test this out on `v6decode.com` as well, look for 'Microsoft UNC'
