### ISSUE TITLE
ipV6 isInSubnet

### ISSUE THREAD

**Issue by clementdevos** [beaugunderson/ip-address#70]
Hey,

I'm currently working with this library to restrict some IP directly or with subnets. 
IsInSubnet works great with IPv4 But i'm having an issue with IPV6 

```
const subnet = new Address6("5800:10C3:E3C3:F1AA:48E3:D923:D494:1/127");
const client = new Address6("5800:10C3:E3C3:F1AA:48E3:D923:D494:0001");
return client.isInSubnet(subnet);
```

This code returns false whereas [v6decode](http://v6decode.com/#address=5800%3A10C3%3AE3C3%3AF1AA%3A48E3%3AD923%3AD494%3A1/127) clearly says the ip is in the subnet.

Here is a dump of the objects 

subnet 
```
Address6 {
  groups: 8,
  v4: false,
  subnet: '/127',
  subnetMask: 127,
  zone: '',
  address: '5800:10C3:E3C3:F1AA:48E3:D923:D494:1/127',
  parsedSubnet: '127',
  addressMinusSuffix: '5800:10C3:E3C3:F1AA:48E3:D923:D494:1',
  elidedGroups: 0,
  valid: true,
  parsedAddress: [ '5800', '10c3', 'e3c3', 'f1aa', '48e3', 'd923', 'd494', '1' ] } 
```
ip
```
Address6 {
  groups: 8,
  v4: false,
  subnet: '/128',
  subnetMask: 128,
  zone: '',
  address: '5801:10C3:E3C3:F1AA:48E3:D923:D494:1',
  addressMinusSuffix: '5801:10C3:E3C3:F1AA:48E3:D923:D494:1',
  elidedGroups: 0,
  valid: true,
  parsedAddress: [ '5801', '10c3', 'e3c3', 'f1aa', '48e3', 'd923', 'd494', '1' ] }

```

It works fine with ipv4 :  `82.126.2.0/28` includes `82.126.2.5` but not `82.126.2.25`

Is this a bug? 

Cheers, 

Clément

**Comment by beaugunderson** [comment]
I've tested this with the exact addresses you mentioned and it works, so if there was a bug it's been fixed since this issue was opened:

```
> (new ip.Address6("5800:10C3:E3C3:F1AA:48E3:D923:D494:0001")).isInSubnet(new ip.Address6("5800:10C3:E3C3:F1AA:48E3:D923:D494:1/127"))
true
```
