### ISSUE TITLE
Update sprintf-js to v1.1.1 to fix global leaks

### ISSUE THREAD

**Issue by aphelionz** [beaugunderson/ip-address#82]
Hello, thanks for your maintenance :)

Please see the issue here: https://github.com/ipfs/js-ipfs/issues/1836#issuecomment-464796264

sprintf-js v1.1.1 fixes a global leak issue in v1.1.0. This would help out a lot of mocha tests! We currently use an exception for these but it would be great to remove them.

**Comment by aphelionz** [comment]
It looks like this is fixed in master! push it to NPM and then I'll close this and go bug the `js-ipfs` folks :D

**Comment by beaugunderson** [comment]
@aphelionz thanks for the nudge, this is now available in `5.9.0` 🎉
