### ISSUE TITLE
Security Vulnerability in ancient lodash

### ISSUE THREAD

**Issue by angelol** [beaugunderson/ip-address#84]
This package uses an ancient version of lodash that has security vulnerability:

https://hackerone.com/reports/380873

Please upgrade to lodash 4.17.11 immediately.

**Comment by gabegorelick** [comment]
Still an issue. Lodash dev recommends using `lodash` package directly rather than the sub-packages. See https://github.com/lodash/lodash/issues/4193#issuecomment-463247496.

**Comment by ceastman-ibm** [comment]
@beaugunderson any update?

**Comment by beaugunderson** [comment]
fixed in 5.9.1, thank you all for your patience 🙏
