### ISSUE TITLE
Any plans to support isMulticast() for IPv4?

### ISSUE THREAD

**Issue by atalis** [beaugunderson/ip-address#86]
It would be great to have isMulticast() check for IPv4.

**Comment by beaugunderson** [comment]
@atalis this looks very straightforward to implement, did you want true/false or do you also want which type of multicast address it is like [the first table here](https://en.wikipedia.org/wiki/Multicast_address)?

**Comment by atalis** [comment]
I think true/false would be sufficient, similar to the one for IPv6.

**Comment by beaugunderson** [comment]
@atalis I've added this in 6.1.0; thanks for the suggestion ✨
