### ISSUE TITLE
Documentation inflates package size in 5.9.1

### ISSUE THREAD

**Issue by cwalther** [beaugunderson/ip-address#88]
Between 5.9.0 and 5.9.1, a _docs_ folder was added to the npm package. Was that intentional? It needlessly increases the distribution size of my application by 1.7 MB. Users of my application have no use for documentation of a sub-dependency, so I don’t think it should be included in a distribution package. I suggest adding _docs_ to _.npmignore_, or even better, using the _files_ field of _package.json_ instead to white-list the things that are actually needed at runtime.

**Comment by beaugunderson** [comment]
great call, this was unintentional—I’ll remove the docs directory asap

**Comment by beaugunderson** [comment]
@cwalther fixed in 6.0.0

**Comment by cwalther** [comment]
Thanks, that was quick!
